### ISSUE TITLE
Warning: Undefined variable $unq in C:\xampp\htdocs\phpsimple-ocr-main\index.php on line 18

### ISSUE THREAD

**Issue by serversamtari** [bnjunge/phpsimple-ocr#1]
Hyy Sir i had trouble with this if i was success uploads the picture

Warning: Undefined variable $unq in C:\xampp\htdocs\phpsimple-ocr-main\index.php on line 18

**Comment by serversamtari** [comment]
![image](https://user-images.githubusercontent.com/113871021/236615373-77aec8d5-77e8-4288-a1dc-8afaabe8572c.png)

**Comment by noshARG** [comment]
facing same issue
